export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILURE = "FETCH_CATEGORIES_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const ADD_ASSIGNMENT_REQUEST = "ADD_ASSIGNMENT_REQUEST";
export const ADD_ASSIGNMENT_SUCCESS = "ADD_ASSIGNMENT_SUCCESS";
export const ADD_ASSIGNMENT_FAILURE = "ADD_ASSIGNMENT_FAILURE";

export const ADD_LESSON_REQUEST = "ADD_LESSON_REQUEST";
export const ADD_LESSON_SUCCESS = "ADD_LESSON_SUCCESS";
export const ADD_LESSON_FAILURE = "ADD_LESSON_FAILURE";


export const FETCH_FREE_COURSES_REQUEST = "FETCH_FREE_COURSES_REQUEST";
export const FETCH_FREE_COURSES_SUCCESS = "FETCH_FREE_COURSES_SUCCESS";
export const FETCH_FREE_COURSES_FAILURE = "FETCH_FREE_COURSES_FAILURE";

export const ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAILURE = "ENROLL_COURSE_FAILURE";
